declare module 'cavitour-shared';
declare module 'cavitour-shared/ntdpFilterMeta';
declare module 'cavitour-shared/placeCheckin';
declare module 'cavitour-shared/lguKind';
declare module 'cavitour-shared/announcements';
declare module 'cavitour-shared/itineraries';
declare module 'cavitour-shared/siteContent';
declare module 'cavitour-shared/mapPins';
declare module 'cavitour-shared/travelAchievements';
