/**
 * Matched offline/demo establishments for web + mobile when Supabase is unavailable.
 * Shape matches `v_cavite_establishments` rows (see migration 20260510120004).
 */
export const DEMO_ESTABLISHMENT_ROWS = [
  {
    id: 'demo-cafe-agapita',
    name: 'Cafe Agapita',
    ta_name: 'Cafe Agapita',
    type_code: 'admin',
    ta_category: 'Cafe',
    ntdp_category: 'Cafe',
    city_mun: 'Silang',
    address: '11 Kapitan Sayas St. Sabutan, Silang, Cavite',
    latitude: 14.2302,
    longitude: 120.9842,
    description:
      'A cozy garden café with a rustic ambiance — perfect for breakfast dates and quiet work sessions surrounded by greenery.',
    searchable_text: 'cafe agapita silang cavite',
    created_at: null,
    lgu_slug: 'admin',
    source_slug: 'admin:demo-cafe-agapita',
    image_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&q=80',
    gallery_urls: null,
    hours: '8:00 AM – 8:00 PM',
    phone: null,
    email: null,
    website: null,
    social_facebook: null,
    social_instagram: null,
    social_twitter: null,
  },
  {
    id: 'demo-tinatangi-cafe',
    name: 'Tinatangi Cafe',
    ta_name: 'Tinatangi Cafe',
    type_code: 'admin',
    ta_category: 'Cafe',
    ntdp_category: 'Cafe',
    city_mun: 'Silang',
    address: 'Jose Abad Santos Avenue, Brgy. Salawag, Silang, Cavite',
    latitude: 14.231,
    longitude: 120.985,
    description:
      'A cozy, Instagrammable coffee spot with alfresco seating, signature drinks, and a relaxed vibe for friends and families.',
    searchable_text: 'tinatangi cafe silang',
    created_at: null,
    lgu_slug: 'admin',
    source_slug: 'admin:demo-tinatangi-cafe',
    image_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80',
    gallery_urls: null,
    hours: '9:00 AM – 9:00 PM',
    phone: null,
    email: null,
    website: null,
    social_facebook: null,
    social_instagram: null,
    social_twitter: null,
  },
  {
    id: 'demo-cafe-10-23',
    name: 'Cafe 10/23',
    ta_name: 'Cafe 10/23',
    type_code: 'admin',
    ta_category: 'Cafe',
    ntdp_category: 'Cafe',
    city_mun: 'Imus',
    address: 'Imus Boulevard, Imus, Cavite',
    latitude: 14.235,
    longitude: 120.988,
    description: 'Neighborhood café along Imus Boulevard known for specialty coffee and all-day brunch.',
    searchable_text: 'cafe 10 23 imus',
    created_at: null,
    lgu_slug: 'admin',
    source_slug: 'admin:demo-cafe-10-23',
    image_url: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&q=80',
    gallery_urls: null,
    hours: '7:00 AM – 10:00 PM',
    phone: null,
    email: null,
    website: null,
    social_facebook: null,
    social_instagram: null,
    social_twitter: null,
  },
  {
    id: 'demo-taal-vista',
    name: 'Taal Vista Hotel',
    ta_name: 'Taal Vista Hotel',
    type_code: 'admin',
    ta_category: 'Hotel',
    ntdp_category: 'Accommodation',
    city_mun: 'Tagaytay City',
    address: 'KM 60 Emilio Aguinaldo Hwy, Tagaytay City, Cavite',
    latitude: 14.128,
    longitude: 120.962,
    description:
      'A hillside hotel offering panoramic views of Taal Volcano, refined rooms, and memorable dining overlooking the ridge.',
    searchable_text: 'taal vista hotel tagaytay',
    created_at: null,
    lgu_slug: 'admin',
    source_slug: 'admin:demo-taal-vista',
    image_url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
    gallery_urls: null,
    hours: 'Open 24 hours',
    phone: null,
    email: null,
    website: null,
    social_facebook: null,
    social_instagram: null,
    social_twitter: null,
  },
];
