import { JAM_SVG, type JamIconName } from './jamSvgMap';

/** Maps former @expo/vector-icons / Ionicons names to bundled Jam Icons (Iconduck / jam-icons, MIT). */
const MAP: Record<string, JamIconName> = {
  'home': 'home',
  'home-outline': 'home',
  'document-text-outline': 'document',
  'map-outline': 'map',
  'map': 'map',
  'car-outline': 'car',
  'car': 'car',
  'person': 'user',
  'person-outline': 'user',
  'notifications-outline': 'bell',
  'notifications': 'bell',
  'options-outline': 'more-vertical',
  /** Chevron-style back (not long arrow). */
  'arrow-back': 'chevron-left',
  'menu': 'menu',
  'filter': 'filter',
  'close': 'close',
  'close-circle': 'close-circle',
  'search': 'search',
  'location': 'map-marker',
  'location-outline': 'map-marker',
  'image-outline': 'picture',
  'image': 'picture',
  'star': 'star',
  'star-outline': 'star',
  'add-circle': 'plus-circle',
  'checkmark': 'check',
  'checkmark-circle': 'check',
  'chevron-forward': 'chevron-right',
  'chevron-up': 'chevron-up',
  'chevron-down': 'chevron-down',
  'bus': 'bus',
  'logo-google': 'google',
  'trash-outline': 'trash',
  'list-outline': 'unordered-list',
  'log-out-outline': 'log-out',
  'navigate': 'compass',
  'navigate-outline': 'compass',
  'compass-outline': 'compass',
  'bookmark-outline': 'bookmark',
  'bookmark': 'bookmark',
  'share-outline': 'share',
  'business': 'building',
  'time': 'clock',
  'time-outline': 'clock',
  'create-outline': 'pencil',
  'ellipse-outline': 'circle',
  'calendar-outline': 'calendar',
  'happy-outline': 'smiley',
  'heart-outline': 'heart',
  'flag-outline': 'flag',
  'alert-circle': 'alert',
  'swap-horizontal': 'shuffle',
  'musical-notes': 'music',
  'water': 'water-drop',
  'restaurant': 'fork',
  'bag': 'shopping-bag',
  'cafe': 'coffee',
  'bed': 'world',
  'leaf': 'leaf',
  'library': 'book',
  'library-outline': 'book',
  'settings-outline': 'cog',
  'train': 'train',
  'plus': 'plus',
};

export function legacyIoniconToJam(ionicon: string): JamIconName {
  if (ionicon in JAM_SVG) return ionicon as JamIconName;
  return MAP[ionicon] ?? 'circle';
}
