import type { AdminItinerary, AdminItineraryStop } from './adminItineraries';

function mapsSearchUrl(lat: number | null | undefined, lng: number | null | undefined): string {
  if (lat == null || lng == null) return '';
  if (!Number.isFinite(lat) || !Number.isFinite(lng)) return '';
  return `https://www.google.com/maps/search/?api=1&query=${lat},${lng}`;
}

function stop(
  clientId: string,
  partial: Omit<AdminItineraryStop, 'clientId' | 'vibeTags' | 'mapsUrl' | 'description'> & {
    description?: string;
    mapsUrl?: string;
    vibeTags?: string[];
  }
): AdminItineraryStop {
  return {
    clientId,
    description: partial.description ?? '',
    vibeTags: partial.vibeTags ?? [],
    mapsUrl: partial.mapsUrl || mapsSearchUrl(partial.venueLat, partial.venueLng),
    name: partial.name,
    timeWindow: partial.timeWindow,
    durationHint: partial.durationHint,
    costType: partial.costType,
    expectTag: partial.expectTag,
    venueName: partial.venueName,
    venueLat: partial.venueLat,
    venueLng: partial.venueLng,
    highlights: partial.highlights,
    establishment: partial.establishment,
  };
}

/** Curated day routes shown in the admin editor (local seed; traveler apps are unchanged). */
export const SEEDED_ADMIN_ITINERARIES: AdminItinerary[] = [
  {
    id: 'highlands',
    title: 'Highlands Getaway',
    subtitle: 'Silang → Tagaytay ridge',
    route: 'Silang → Tagaytay',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',
    durationLabel: '1 day',
    priceTier: 2,
    priceTierLabel: 'Moderate',
    tags: ['Views', 'Food'],
    summary:
      'Upland farms, outlet shopping, and ridge viewpoints — a full Silang-to-Tagaytay day using verified Cavite establishments.',
    itineraryHighlights: [
      'Starts in Silang cafés and farms, ends at Tagaytay lookouts',
      'Stops ordered for a one-way ridge day',
    ],
    bestTime: 'Weekday mornings · clearer Dec–May',
    status: 'published',
    featured: true,
    tips: [],
    stopList: [
      stop('highlands-1', {
        name: 'Farm & café morning',
        timeWindow: '08:00 AM – 10:00 AM',
        durationHint: '~2 hrs',
        costType: 'Pay per Order',
        expectTag: 'Sip & Snack',
        highlights: [
          'Order a signature brew and sit facing the greenhouse',
          'Walk the herb garden before the ridge climb',
        ],
        venueName: 'Gourmet Farms, Inc.',
        venueLat: 14.223624,
        venueLng: 120.9741497,
        establishment: { placeId: '93e95b24-12e1-4bb6-a69e-100fbd9137e1' },
      }),
      stop('highlands-2', {
        name: 'Designer outlet break',
        timeWindow: '10:30 AM – 12:30 PM',
        durationHint: '~2 hrs',
        costType: 'Pay per Order',
        expectTag: 'Souvenir Shopping',
        highlights: [
          'Browse walkable retail lanes for souvenirs',
          'Grab a light snack before the lookout stretch',
        ],
        venueName: 'Acienda Designer Outlet',
        venueLat: 14.1836088,
        venueLng: 120.9611198,
        establishment: { placeId: '9e65d893-01c9-4200-9dc0-505392aca8bc' },
      }),
      stop('highlands-3', {
        name: 'Ridge picnic stop',
        timeWindow: '01:00 PM – 03:00 PM',
        durationHint: '~2 hrs',
        costType: 'Free Entry',
        expectTag: 'Sip & Snack',
        highlights: [
          'Pick a Taal-facing lawn for a picnic pause',
          'Stay for clearer afternoon views on weekdays',
        ],
        venueName: 'Tagaytay Picnic Grove',
        venueLat: 14.0992606,
        venueLng: 120.9391818,
        establishment: { placeId: 'a22975da-b031-4baa-9353-d9dbabe980a2' },
      }),
      stop('highlands-4', {
        name: 'Skyline finale',
        timeWindow: '03:30 PM – 05:00 PM',
        durationHint: '~1.5 hrs',
        costType: 'Entrance Fee',
        expectTag: '',
        highlights: [
          'Arrive before late haze for the skyline view',
          'Bring a light jacket for the breeze after 4 PM',
        ],
        venueName: "People's Park in the Sky",
        venueLat: 14.1458,
        venueLng: 121.0264,
        establishment: { placeId: '693db4c7-29af-4571-8fe7-4f40a2bf2f4d' },
      }),
    ],
  },
  {
    id: 'heritage',
    title: 'Heritage & Horizons Trail',
    subtitle: 'Imus → Bacoor → Noveleta',
    route: 'Imus → Kawit → Noveleta',
    image: 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=800&h=600&fit=crop&q=80',
    durationLabel: 'Full day',
    priceTier: 1,
    priceTierLabel: 'Budget',
    tags: ['Culture', 'History', 'Heritage'],
    summary: '',
    itineraryHighlights: [],
    bestTime: 'Morning to late afternoon',
    status: 'published',
    featured: false,
    tips: [],
    stopList: [
      stop('heritage-1', {
        name: 'National flag shrine',
        timeWindow: '08:00 AM – 09:30 AM',
        durationHint: '~1.5 hrs',
        costType: 'Free Entry',
        expectTag: '',
        highlights: [
          'Read the declaration markers before crowds build',
          'Photograph the grounds while light is still soft',
        ],
        venueName: 'Imus Historical Landmark',
        venueLat: 14.4297798,
        venueLng: 120.9360565,
        establishment: { placeId: '6b95f300-1cd6-4097-ba75-371a75041aca' },
      }),
      stop('heritage-2', {
        name: 'Imus cathedral',
        timeWindow: '09:45 AM – 11:00 AM',
        durationHint: '~1.25 hrs',
        costType: 'Free Entry',
        expectTag: '',
        highlights: ['Walk the plaza and cathedral facade', 'Step inside if mass or visiting hours allow'],
        venueName: 'Imus Cathedral',
        venueLat: 14.4297798,
        venueLng: 120.9360565,
        establishment: { placeId: '9194ec49-4a06-418b-b6b9-582c96737e25' },
      }),
      stop('heritage-3', {
        name: 'Ancestral corridor',
        timeWindow: '11:30 AM – 01:30 PM',
        durationHint: '~2 hrs',
        costType: 'Entrance Fee',
        expectTag: '',
        highlights: ['Tour the ancestral house interiors if open', 'Note architectural details along the corridor'],
        venueName: 'Cuenca Ancestral House',
        venueLat: 14.4596033,
        venueLng: 120.9598169,
        establishment: { placeId: '490c7feb-ecd4-4391-94ae-58486b908d10' },
      }),
      stop('heritage-4', {
        name: 'Noveleta tribunal',
        timeWindow: '02:00 PM – 03:30 PM',
        durationHint: '~1.5 hrs',
        costType: 'Free Entry',
        expectTag: '',
        highlights: ['See the preserved civic landmark up close', 'Finish with a short walk toward the shore'],
        venueName: 'Tribunal House of Noveleta',
        venueLat: 14.4278394,
        venueLng: 120.8808454,
        establishment: { placeId: '3d882e76-90b2-42ad-923c-e5056446cdbf' },
      }),
    ],
  },
  {
    id: 'coastal',
    title: 'Coastal Calm Journey',
    subtitle: 'Tanza → Julugan → Bacoor',
    route: 'Tanza → Naic → Maragondon',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80',
    durationLabel: '1 day',
    priceTier: 2,
    priceTierLabel: 'Moderate',
    tags: ['Beach', 'Seafood', 'Coast'],
    summary: '',
    itineraryHighlights: [],
    bestTime: 'Late morning to sunset',
    status: 'draft',
    featured: false,
    tips: [],
    stopList: [
      stop('coastal-1', {
        name: 'Town plaza',
        timeWindow: '09:00 AM – 10:30 AM',
        durationHint: '~1.5 hrs',
        costType: 'Free Entry',
        expectTag: '',
        highlights: ['Start at the central plaza for orientation photos'],
        venueName: 'Plaza de San Agustin',
        venueLat: 14.400675,
        venueLng: 120.8572845,
        establishment: { placeId: '5b044510-baec-4acb-80f9-0945e7fc7865' },
      }),
      stop('coastal-2', {
        name: 'Hacienda grounds',
        timeWindow: '10:45 AM – 12:15 PM',
        durationHint: '~1.5 hrs',
        costType: 'Entrance Fee',
        expectTag: '',
        highlights: ['Stroll the heritage grounds at an easy pace'],
        venueName: 'Casa Hacienda de Tanza',
        venueLat: 14.400675,
        venueLng: 120.8572845,
        establishment: { placeId: '5fbb3395-a820-478b-a72b-d3ca6cd0adb5' },
      }),
      stop('coastal-3', {
        name: 'Fish port',
        timeWindow: '12:30 PM – 02:30 PM',
        durationHint: '~2 hrs',
        costType: 'Pay per Order',
        expectTag: 'Full Meal',
        highlights: ['Try a seafood plate while watching harbor traffic'],
        venueName: 'Julugan Fish Port',
        venueLat: 14.400675,
        venueLng: 120.8572845,
        establishment: { placeId: '606dfa63-4830-4fd7-9a8f-36c98a8b92d6' },
      }),
      stop('coastal-4', {
        name: 'Mangrove walk',
        timeWindow: '03:00 PM – 05:00 PM',
        durationHint: '~2 hrs',
        costType: 'Free Entry',
        expectTag: '',
        highlights: ['Walk the boardwalk toward late-day light'],
        venueName: 'Bacoor Mangrove Eco-Park',
        venueLat: 14.4596033,
        venueLng: 120.9598169,
        establishment: { placeId: 'b672165c-2baf-4992-bf29-a19bd8c3cd76' },
      }),
    ],
  },
  {
    id: 'bloomfields',
    title: 'Bloomfields & Breezes Route',
    subtitle: 'Silang → Amadeo → General Trias → Dasmariñas',
    route: 'Silang → General Trias → Dasmariñas',
    image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80',
    durationLabel: 'Half day',
    priceTier: 2,
    priceTierLabel: 'Moderate',
    tags: ['Gardens', 'Cafe'],
    summary: '',
    itineraryHighlights: [],
    bestTime: 'Early morning',
    status: 'flagged',
    featured: false,
    tips: [],
    stopList: [
      stop('bloom-1', {
        name: 'Silang farms',
        timeWindow: '07:30 AM – 09:00 AM',
        durationHint: '~1.5 hrs',
        costType: 'Pay per Order',
        expectTag: 'Sip & Snack',
        highlights: ['Walk the farm retail lanes while it is still cool'],
        venueName: 'Gourmet Farms, Inc.',
        venueLat: 14.223624,
        venueLng: 120.9741497,
        establishment: { placeId: '93e95b24-12e1-4bb6-a69e-100fbd9137e1' },
      }),
      stop('bloom-2', {
        name: 'Coffee heritage',
        timeWindow: '09:15 AM – 10:15 AM',
        durationHint: '~1 hr',
        costType: 'Free Entry',
        expectTag: '',
        highlights: ['Stop at the coffee mural for a culture pause'],
        venueName: 'Amadeo Coffee Mural',
        venueLat: 14.1704,
        venueLng: 120.9236,
        establishment: { placeId: '9316cff4-5bdd-4a20-a45c-2d96b67476ef' },
      }),
      stop('bloom-3', {
        name: 'Café break',
        timeWindow: '10:30 AM – 11:30 AM',
        durationHint: '~1 hr',
        costType: 'Pay per Order',
        expectTag: 'Sip & Snack',
        highlights: ['Sit down for a café plate before the city leg'],
        venueName: 'Felize Cafe',
        venueLat: 14.363722,
        venueLng: 120.9058041,
        establishment: { placeId: '7fbde5ad-390a-41cf-becd-17d5fbfce07b' },
      }),
      stop('bloom-4', {
        name: 'Museum close',
        timeWindow: '11:45 AM – 12:45 PM',
        durationHint: '~1 hr',
        costType: 'Entrance Fee',
        expectTag: '',
        highlights: ['Finish with indoor exhibits out of midday sun'],
        venueName: 'Museo De La Salle',
        venueLat: 14.3209977,
        venueLng: 120.9610387,
        establishment: { placeId: 'e9cc0be2-b7c3-4c68-81a3-79455a689a92' },
      }),
    ],
  },
];
