-- STA-v3 Cavite 2025 — per-LGU establishment tables (generated by import-sta-cavite-v3.mjs)
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS public.places_alfonso (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ta_name TEXT NOT NULL,
  type_code TEXT,
  ta_category TEXT,
  ntdp_category TEXT,
  city_mun TEXT,
  address TEXT NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  description TEXT,
  searchable_text TEXT NOT NULL,
  search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(searchable_text, ''))) STORED,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS places_alfonso_searchable_trgm ON public.places_alfonso USING GIN (searchable_text gin_trgm_ops);
CREATE INDEX IF NOT EXISTS places_alfonso_search_vec ON public.places_alfonso USING GIN (search_vector);
ALTER TABLE public.places_alfonso ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read places_alfonso" ON public.places_alfonso;
CREATE POLICY "Public read places_alfonso" ON public.places_alfonso FOR SELECT USING (true);
GRANT SELECT ON public.places_alfonso TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public.places_amadeo (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ta_name TEXT NOT NULL,
  type_code TEXT,
  ta_category TEXT,
  ntdp_category TEXT,
  city_mun TEXT,
  address TEXT NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  description TEXT,
  searchable_text TEXT NOT NULL,
  search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(searchable_text, ''))) STORED,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS places_amadeo_searchable_trgm ON public.places_amadeo USING GIN (searchable_text gin_trgm_ops);
CREATE INDEX IF NOT EXISTS places_amadeo_search_vec ON public.places_amadeo USING GIN (search_vector);
ALTER TABLE public.places_amadeo ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read places_amadeo" ON public.places_amadeo;
CREATE POLICY "Public read places_amadeo" ON public.places_amadeo FOR SELECT USING (true);
GRANT SELECT ON public.places_amadeo TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public.places_bacoor_city (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ta_name TEXT NOT NULL,
  type_code TEXT,
  ta_category TEXT,
  ntdp_category TEXT,
  city_mun TEXT,
  address TEXT NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  description TEXT,
  searchable_text TEXT NOT NULL,
  search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(searchable_text, ''))) STORED,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS places_bacoor_city_searchable_trgm ON public.places_bacoor_city USING GIN (searchable_text gin_trgm_ops);
CREATE INDEX IF NOT EXISTS places_bacoor_city_search_vec ON public.places_bacoor_city USING GIN (search_vector);
ALTER TABLE public.places_bacoor_city ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read places_bacoor_city" ON public.places_bacoor_city;
CREATE POLICY "Public read places_bacoor_city" ON public.places_bacoor_city FOR SELECT USING (true);
GRANT SELECT ON public.places_bacoor_city TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public.places_carmona_city (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ta_name TEXT NOT NULL,
  type_code TEXT,
  ta_category TEXT,
  ntdp_category TEXT,
  city_mun TEXT,
  address TEXT NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  description TEXT,
  searchable_text TEXT NOT NULL,
  search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(searchable_text, ''))) STORED,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS places_carmona_city_searchable_trgm ON public.places_carmona_city USING GIN (searchable_text gin_trgm_ops);
CREATE INDEX IF NOT EXISTS places_carmona_city_search_vec ON public.places_carmona_city USING GIN (search_vector);
ALTER TABLE public.places_carmona_city ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read places_carmona_city" ON public.places_carmona_city;
CREATE POLICY "Public read places_carmona_city" ON public.places_carmona_city FOR SELECT USING (true);
GRANT SELECT ON public.places_carmona_city TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public.places_cavite_city (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ta_name TEXT NOT NULL,
  type_code TEXT,
  ta_category TEXT,
  ntdp_category TEXT,
  city_mun TEXT,
  address TEXT NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  description TEXT,
  searchable_text TEXT NOT NULL,
  search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(searchable_text, ''))) STORED,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS places_cavite_city_searchable_trgm ON public.places_cavite_city USING GIN (searchable_text gin_trgm_ops);
CREATE INDEX IF NOT EXISTS places_cavite_city_search_vec ON public.places_cavite_city USING GIN (search_vector);
ALTER TABLE public.places_cavite_city ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read places_cavite_city" ON public.places_cavite_city;
CREATE POLICY "Public read places_cavite_city" ON public.places_cavite_city FOR SELECT USING (true);
GRANT SELECT ON public.places_cavite_city TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public.places_dasmarinas_city (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ta_name TEXT NOT NULL,
  type_code TEXT,
  ta_category TEXT,
  ntdp_category TEXT,
  city_mun TEXT,
  address TEXT NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  description TEXT,
  searchable_text TEXT NOT NULL,
  search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(searchable_text, ''))) STORED,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS places_dasmarinas_city_searchable_trgm ON public.places_dasmarinas_city USING GIN (searchable_text gin_trgm_ops);
CREATE INDEX IF NOT EXISTS places_dasmarinas_city_search_vec ON public.places_dasmarinas_city USING GIN (search_vector);
ALTER TABLE public.places_dasmarinas_city ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read places_dasmarinas_city" ON public.places_dasmarinas_city;
CREATE POLICY "Public read places_dasmarinas_city" ON public.places_dasmarinas_city FOR SELECT USING (true);
GRANT SELECT ON public.places_dasmarinas_city TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public.places_general_mariano_alvarez (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ta_name TEXT NOT NULL,
  type_code TEXT,
  ta_category TEXT,
  ntdp_category TEXT,
  city_mun TEXT,
  address TEXT NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  description TEXT,
  searchable_text TEXT NOT NULL,
  search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(searchable_text, ''))) STORED,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS places_general_mariano_alvarez_searchable_trgm ON public.places_general_mariano_alvarez USING GIN (searchable_text gin_trgm_ops);
CREATE INDEX IF NOT EXISTS places_general_mariano_alvarez_search_vec ON public.places_general_mariano_alvarez USING GIN (search_vector);
ALTER TABLE public.places_general_mariano_alvarez ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read places_general_mariano_alvarez" ON public.places_general_mariano_alvarez;
CREATE POLICY "Public read places_general_mariano_alvarez" ON public.places_general_mariano_alvarez FOR SELECT USING (true);
GRANT SELECT ON public.places_general_mariano_alvarez TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public.places_general_trias_city (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ta_name TEXT NOT NULL,
  type_code TEXT,
  ta_category TEXT,
  ntdp_category TEXT,
  city_mun TEXT,
  address TEXT NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  description TEXT,
  searchable_text TEXT NOT NULL,
  search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(searchable_text, ''))) STORED,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS places_general_trias_city_searchable_trgm ON public.places_general_trias_city USING GIN (searchable_text gin_trgm_ops);
CREATE INDEX IF NOT EXISTS places_general_trias_city_search_vec ON public.places_general_trias_city USING GIN (search_vector);
ALTER TABLE public.places_general_trias_city ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read places_general_trias_city" ON public.places_general_trias_city;
CREATE POLICY "Public read places_general_trias_city" ON public.places_general_trias_city FOR SELECT USING (true);
GRANT SELECT ON public.places_general_trias_city TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public.places_imus_city (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ta_name TEXT NOT NULL,
  type_code TEXT,
  ta_category TEXT,
  ntdp_category TEXT,
  city_mun TEXT,
  address TEXT NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  description TEXT,
  searchable_text TEXT NOT NULL,
  search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(searchable_text, ''))) STORED,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS places_imus_city_searchable_trgm ON public.places_imus_city USING GIN (searchable_text gin_trgm_ops);
CREATE INDEX IF NOT EXISTS places_imus_city_search_vec ON public.places_imus_city USING GIN (search_vector);
ALTER TABLE public.places_imus_city ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read places_imus_city" ON public.places_imus_city;
CREATE POLICY "Public read places_imus_city" ON public.places_imus_city FOR SELECT USING (true);
GRANT SELECT ON public.places_imus_city TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public.places_indang (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ta_name TEXT NOT NULL,
  type_code TEXT,
  ta_category TEXT,
  ntdp_category TEXT,
  city_mun TEXT,
  address TEXT NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  description TEXT,
  searchable_text TEXT NOT NULL,
  search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(searchable_text, ''))) STORED,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS places_indang_searchable_trgm ON public.places_indang USING GIN (searchable_text gin_trgm_ops);
CREATE INDEX IF NOT EXISTS places_indang_search_vec ON public.places_indang USING GIN (search_vector);
ALTER TABLE public.places_indang ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read places_indang" ON public.places_indang;
CREATE POLICY "Public read places_indang" ON public.places_indang FOR SELECT USING (true);
GRANT SELECT ON public.places_indang TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public.places_magallanes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ta_name TEXT NOT NULL,
  type_code TEXT,
  ta_category TEXT,
  ntdp_category TEXT,
  city_mun TEXT,
  address TEXT NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  description TEXT,
  searchable_text TEXT NOT NULL,
  search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(searchable_text, ''))) STORED,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS places_magallanes_searchable_trgm ON public.places_magallanes USING GIN (searchable_text gin_trgm_ops);
CREATE INDEX IF NOT EXISTS places_magallanes_search_vec ON public.places_magallanes USING GIN (search_vector);
ALTER TABLE public.places_magallanes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read places_magallanes" ON public.places_magallanes;
CREATE POLICY "Public read places_magallanes" ON public.places_magallanes FOR SELECT USING (true);
GRANT SELECT ON public.places_magallanes TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public.places_mendez_nunez (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ta_name TEXT NOT NULL,
  type_code TEXT,
  ta_category TEXT,
  ntdp_category TEXT,
  city_mun TEXT,
  address TEXT NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  description TEXT,
  searchable_text TEXT NOT NULL,
  search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(searchable_text, ''))) STORED,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS places_mendez_nunez_searchable_trgm ON public.places_mendez_nunez USING GIN (searchable_text gin_trgm_ops);
CREATE INDEX IF NOT EXISTS places_mendez_nunez_search_vec ON public.places_mendez_nunez USING GIN (search_vector);
ALTER TABLE public.places_mendez_nunez ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read places_mendez_nunez" ON public.places_mendez_nunez;
CREATE POLICY "Public read places_mendez_nunez" ON public.places_mendez_nunez FOR SELECT USING (true);
GRANT SELECT ON public.places_mendez_nunez TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public.places_noveleta (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ta_name TEXT NOT NULL,
  type_code TEXT,
  ta_category TEXT,
  ntdp_category TEXT,
  city_mun TEXT,
  address TEXT NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  description TEXT,
  searchable_text TEXT NOT NULL,
  search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(searchable_text, ''))) STORED,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS places_noveleta_searchable_trgm ON public.places_noveleta USING GIN (searchable_text gin_trgm_ops);
CREATE INDEX IF NOT EXISTS places_noveleta_search_vec ON public.places_noveleta USING GIN (search_vector);
ALTER TABLE public.places_noveleta ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read places_noveleta" ON public.places_noveleta;
CREATE POLICY "Public read places_noveleta" ON public.places_noveleta FOR SELECT USING (true);
GRANT SELECT ON public.places_noveleta TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public.places_silang (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ta_name TEXT NOT NULL,
  type_code TEXT,
  ta_category TEXT,
  ntdp_category TEXT,
  city_mun TEXT,
  address TEXT NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  description TEXT,
  searchable_text TEXT NOT NULL,
  search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(searchable_text, ''))) STORED,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS places_silang_searchable_trgm ON public.places_silang USING GIN (searchable_text gin_trgm_ops);
CREATE INDEX IF NOT EXISTS places_silang_search_vec ON public.places_silang USING GIN (search_vector);
ALTER TABLE public.places_silang ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read places_silang" ON public.places_silang;
CREATE POLICY "Public read places_silang" ON public.places_silang FOR SELECT USING (true);
GRANT SELECT ON public.places_silang TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public.places_tagaytay_city (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ta_name TEXT NOT NULL,
  type_code TEXT,
  ta_category TEXT,
  ntdp_category TEXT,
  city_mun TEXT,
  address TEXT NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  description TEXT,
  searchable_text TEXT NOT NULL,
  search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(searchable_text, ''))) STORED,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS places_tagaytay_city_searchable_trgm ON public.places_tagaytay_city USING GIN (searchable_text gin_trgm_ops);
CREATE INDEX IF NOT EXISTS places_tagaytay_city_search_vec ON public.places_tagaytay_city USING GIN (search_vector);
ALTER TABLE public.places_tagaytay_city ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read places_tagaytay_city" ON public.places_tagaytay_city;
CREATE POLICY "Public read places_tagaytay_city" ON public.places_tagaytay_city FOR SELECT USING (true);
GRANT SELECT ON public.places_tagaytay_city TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public.places_tanza (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ta_name TEXT NOT NULL,
  type_code TEXT,
  ta_category TEXT,
  ntdp_category TEXT,
  city_mun TEXT,
  address TEXT NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  description TEXT,
  searchable_text TEXT NOT NULL,
  search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(searchable_text, ''))) STORED,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS places_tanza_searchable_trgm ON public.places_tanza USING GIN (searchable_text gin_trgm_ops);
CREATE INDEX IF NOT EXISTS places_tanza_search_vec ON public.places_tanza USING GIN (search_vector);
ALTER TABLE public.places_tanza ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read places_tanza" ON public.places_tanza;
CREATE POLICY "Public read places_tanza" ON public.places_tanza FOR SELECT USING (true);
GRANT SELECT ON public.places_tanza TO anon, authenticated;

CREATE TABLE IF NOT EXISTS public.places_trece_martires_city (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ta_name TEXT NOT NULL,
  type_code TEXT,
  ta_category TEXT,
  ntdp_category TEXT,
  city_mun TEXT,
  address TEXT NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  description TEXT,
  searchable_text TEXT NOT NULL,
  search_vector tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(searchable_text, ''))) STORED,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS places_trece_martires_city_searchable_trgm ON public.places_trece_martires_city USING GIN (searchable_text gin_trgm_ops);
CREATE INDEX IF NOT EXISTS places_trece_martires_city_search_vec ON public.places_trece_martires_city USING GIN (search_vector);
ALTER TABLE public.places_trece_martires_city ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public read places_trece_martires_city" ON public.places_trece_martires_city;
CREATE POLICY "Public read places_trece_martires_city" ON public.places_trece_martires_city FOR SELECT USING (true);
GRANT SELECT ON public.places_trece_martires_city TO anon, authenticated;

DROP VIEW IF EXISTS public.v_cavite_establishments;
CREATE VIEW public.v_cavite_establishments AS
SELECT id, ta_name AS name, ta_name, type_code, ta_category, ntdp_category, city_mun, address, latitude, longitude, description, searchable_text, created_at, 'alfonso'::text AS lgu_slug FROM public.places_alfonso
UNION ALL
SELECT id, ta_name AS name, ta_name, type_code, ta_category, ntdp_category, city_mun, address, latitude, longitude, description, searchable_text, created_at, 'amadeo'::text AS lgu_slug FROM public.places_amadeo
UNION ALL
SELECT id, ta_name AS name, ta_name, type_code, ta_category, ntdp_category, city_mun, address, latitude, longitude, description, searchable_text, created_at, 'bacoor_city'::text AS lgu_slug FROM public.places_bacoor_city
UNION ALL
SELECT id, ta_name AS name, ta_name, type_code, ta_category, ntdp_category, city_mun, address, latitude, longitude, description, searchable_text, created_at, 'carmona_city'::text AS lgu_slug FROM public.places_carmona_city
UNION ALL
SELECT id, ta_name AS name, ta_name, type_code, ta_category, ntdp_category, city_mun, address, latitude, longitude, description, searchable_text, created_at, 'cavite_city'::text AS lgu_slug FROM public.places_cavite_city
UNION ALL
SELECT id, ta_name AS name, ta_name, type_code, ta_category, ntdp_category, city_mun, address, latitude, longitude, description, searchable_text, created_at, 'dasmarinas_city'::text AS lgu_slug FROM public.places_dasmarinas_city
UNION ALL
SELECT id, ta_name AS name, ta_name, type_code, ta_category, ntdp_category, city_mun, address, latitude, longitude, description, searchable_text, created_at, 'general_mariano_alvarez'::text AS lgu_slug FROM public.places_general_mariano_alvarez
UNION ALL
SELECT id, ta_name AS name, ta_name, type_code, ta_category, ntdp_category, city_mun, address, latitude, longitude, description, searchable_text, created_at, 'general_trias_city'::text AS lgu_slug FROM public.places_general_trias_city
UNION ALL
SELECT id, ta_name AS name, ta_name, type_code, ta_category, ntdp_category, city_mun, address, latitude, longitude, description, searchable_text, created_at, 'imus_city'::text AS lgu_slug FROM public.places_imus_city
UNION ALL
SELECT id, ta_name AS name, ta_name, type_code, ta_category, ntdp_category, city_mun, address, latitude, longitude, description, searchable_text, created_at, 'indang'::text AS lgu_slug FROM public.places_indang
UNION ALL
SELECT id, ta_name AS name, ta_name, type_code, ta_category, ntdp_category, city_mun, address, latitude, longitude, description, searchable_text, created_at, 'magallanes'::text AS lgu_slug FROM public.places_magallanes
UNION ALL
SELECT id, ta_name AS name, ta_name, type_code, ta_category, ntdp_category, city_mun, address, latitude, longitude, description, searchable_text, created_at, 'mendez_nunez'::text AS lgu_slug FROM public.places_mendez_nunez
UNION ALL
SELECT id, ta_name AS name, ta_name, type_code, ta_category, ntdp_category, city_mun, address, latitude, longitude, description, searchable_text, created_at, 'noveleta'::text AS lgu_slug FROM public.places_noveleta
UNION ALL
SELECT id, ta_name AS name, ta_name, type_code, ta_category, ntdp_category, city_mun, address, latitude, longitude, description, searchable_text, created_at, 'silang'::text AS lgu_slug FROM public.places_silang
UNION ALL
SELECT id, ta_name AS name, ta_name, type_code, ta_category, ntdp_category, city_mun, address, latitude, longitude, description, searchable_text, created_at, 'tagaytay_city'::text AS lgu_slug FROM public.places_tagaytay_city
UNION ALL
SELECT id, ta_name AS name, ta_name, type_code, ta_category, ntdp_category, city_mun, address, latitude, longitude, description, searchable_text, created_at, 'tanza'::text AS lgu_slug FROM public.places_tanza
UNION ALL
SELECT id, ta_name AS name, ta_name, type_code, ta_category, ntdp_category, city_mun, address, latitude, longitude, description, searchable_text, created_at, 'trece_martires_city'::text AS lgu_slug FROM public.places_trece_martires_city;

ALTER VIEW public.v_cavite_establishments SET (security_invoker = true);
GRANT SELECT ON public.v_cavite_establishments TO anon, authenticated;
