-- New landing CMS keys only. Does not overwrite existing site_content rows.
INSERT INTO public.site_content (key, value) VALUES
  ('landing.hero.cta_href', '/signup'),
  ('landing.hero.image_url', 'https://www.beautyofthephilippines.com/wp-content/uploads/2007/05/Corregidor-Island-2025-11-22-2025-11-22-DJI_0873_HDR-1-marianosayno-2-0-1536x1023.jpg'),
  ('landing.hero.image_alt', 'Aerial view of Corregidor Island, Cavite'),
  ('landing.nav.destinations', 'Top Destinations'),
  ('landing.nav.trails', 'Day Trails'),
  ('landing.nav.why', 'Why Tara, Cavite!'),
  ('landing.why.heading', 'Why Choose Tara, Cavite!'),
  ('landing.why.body', 'Built specifically for commute-ready exploration, heritage discovery, and effortless travel planning across the province.'),
  ('landing.why.pill_1', 'Interactive route maps'),
  ('landing.why.pill_2', 'Custom saved lists'),
  ('landing.why.pill_3', 'ESTABLISHMENT & TOURISM ANNOUNCEMENTS'),
  ('landing.why.stat_establishments', 'Verified Establishments & Attractions'),
  ('landing.why.stat_municipalities', 'Cities & Municipalities Covered'),
  ('landing.why.stat_routes', 'Day Routes with Sequential Stop Timelines'),
  ('landing.why.live_value', 'Live Updates'),
  ('landing.why.live_label', 'Official travel notices from local establishments and Provincial Tourism'),
  ('landing.features.heading', 'Features we provide'),
  ('landing.features.1.n', '01'),
  ('landing.features.1.title', 'Step-by-Step Route Schedules'),
  ('landing.features.1.body', 'View detailed itinerary stops complete with recommended stay durations, free/paid entry tags, and quick links to navigation.'),
  ('landing.features.1.image_url', 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=900&q=80'),
  ('landing.features.1.href', '/itinerary'),
  ('landing.features.2.n', '02'),
  ('landing.features.2.title', 'Personalized Saved Lists & Check-ins'),
  ('landing.features.2.body', 'Group your favorite spots into custom private lists, leave reviews, and track your travel history with location check-ins.'),
  ('landing.features.2.image_url', 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?auto=format&fit=crop&w=900&q=80'),
  ('landing.features.2.href', '/saved'),
  ('landing.features.3.n', '03'),
  ('landing.features.3.title', 'Turn-by-Turn Navigation'),
  ('landing.features.3.body', 'Get direct travel routes, estimated travel times, and traffic condition updates for driving or commuting.'),
  ('landing.features.3.image_url', 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=900&q=80'),
  ('landing.features.3.href', '/search'),
  ('landing.features.4.n', '04'),
  ('landing.features.4.title', 'Establishment & Tourism Notices'),
  ('landing.features.4.body', 'Stay informed with direct updates, local event schedules, and travel news posted by verified establishments and the Provincial Tourism Office of Cavite.'),
  ('landing.features.4.image_url', 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=900&q=80'),
  ('landing.features.4.href', '/announcements'),
  ('landing.destinations.heading', 'Explore Cavite’s Top Destinations'),
  ('landing.destinations.body', 'Verified spots drawn directly from the Cavite tourism catalog. Open any tile to search that place.'),
  ('landing.destinations.cta', 'See more places'),
  ('landing.destinations.cta_href', '/search'),
  ('landing.trails.heading', 'Curated Day Trails'),
  ('landing.trails.body', 'Ready-to-use travel routes linking verified destinations with estimated timings.'),
  ('landing.trails.cta', 'View itineraries'),
  ('landing.trails.cta_href', '/itinerary'),
  ('landing.signup.heading', 'Ready to start your Cavite journey?'),
  ('landing.signup.body', 'Create a free traveler account to save places, log your check-ins, unlock community reviews, and follow curated routes.'),
  ('landing.signup.primary', 'Create Free Account'),
  ('landing.signup.primary_href', '/signup'),
  ('landing.signup.secondary', 'Browse Map First'),
  ('landing.signup.secondary_href', '/search'),
  ('landing.footer.copyright', '© 2026 Tara, Cavite! All rights reserved.')
ON CONFLICT (key) DO NOTHING;
